default_language_version:
  python: python3.9

default_stages: [commit, push]

repos:
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        exclude: tests/

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/PyCQA/autoflake
    rev: v2.1.1
    hooks:
    - id: autoflake
      args: [--in-place, --remove-all-unused-imports]
      additional_dependencies: [
          'flake8-blind-except',
          'flake8-deprecated',
          'flake8-string-format',
          'flake8-bugbear',
          'flake8-comprehensions',
          'flake8-implicit-str-concat',
          'pydocstyle>=5.0.0',
          'flake8-pep3101',
          'flake8-polyfill',
          # 'flake8-coding',
          # 'flake8-print',
          # 'flake8-docstrings',
          # 'flake8-quotes',
      ]

  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
    - id: flake8
      # args: [--ignore=D100,D103,E902]
      additional_dependencies: [
          'flake8-blind-except',
          'flake8-deprecated',
          'flake8-string-format',
          'flake8-bugbear',
          'flake8-comprehensions',
          'flake8-implicit-str-concat',
          'pydocstyle>=5.0.0',
          'flake8-pep3101',
          'flake8-polyfill',
          # 'flake8-coding',
          # 'flake8-print',
          # 'flake8-docstrings',
          # 'flake8-quotes',
      ]

  # Tool for automatically reordering python imports. Similar to isort but uses static analysis more.
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v3.9.0
    hooks:
    - id: reorder-python-imports
      args: [--py36-plus]
      # args: [--application-directories=./src, --py36-plus]

  # A tool (and pre-commit hook) to automatically upgrade syntax for newer versions of the language.
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.3.2
    hooks:
    - id: pyupgrade
      args: [--py36-plus]

  # A type checkers help ensure that you're using variables and functions in your code correctly.
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.2.0
    hooks:
    - id: mypy
      # files: ^src/
      # args: []

  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.19.1
    hooks:
    - id: gitlint

  # - repo: local
  #     hooks:
  #       - id: pylint
  #         name: pylint
  #         entry: poetry run pylint app/
  #         language: system
  #         always_run: true
  #         pass_filenames: false
  #       - id: create requirements
  #         name: create requirements
  #         entry: sh write_requirements.sh
  #         language: system
  #         always_run: true
  #         pass_filenames: false


# name: pre-commit

# on:
#   pull_request:
#   push:
#     branches: [main]

# jobs:
#   pre-commit:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v3
#       with:
#         ref: ${{ github.head_ref }}
#     - uses: actions/setup-python@v3
#     - uses: pre-commit/action@v3.0.0
